services:
  app:
    build: .
    container_name: auth_medods
    environment:
      JWT_SECRET: key
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: medods
      DB_HOST: db
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:bookworm
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medods
    ports:
      - "5432:5432"
